### ISSUE TITLE
Błąd w boot.ipxe

### ISSUE THREAD

**Issue by kedarnok** [bockpl/bocm#1]
Należy poprawić plik boot.ipxe
Jest:
:disk_info
set TEMPLATE ubuntu18.04dev
set PARAMS disk_info
goto ububoot

Ma być:
:disk_info
set TEMPLATE ubuntu18.04dev
set PARAMS disk_info
goto base

**Comment by seweryn-S** [comment]
Poprawione w [https://github.com/bockpl/bocm/commit/ec5808d16bd003c6532ff24d98692c7cbe67a423](url)

**Comment by seweryn-S** [comment]
https://github.com/bockpl/bocm/commit/ec5808d16bd003c6532ff24d98692c7cbe67a423
