### ISSUE TITLE
Problem z wyborem odpowiedniej karty sieciowej

### ISSUE THREAD

**Issue by przemyslawtrzeciak** [bockpl/bocm#3]
W procesie bootowania użyty jest do konfiguracji pierwszy interfejs sieciowy (eth0), zaraz po wskazaniu w ipxe obrazu z którego bootoujemy. W przypadku systemów z grupą kart sieciowych (np.: zintegrowanych 10Gbs oraz 10Gbs w SFP+) nie można wskazać która karta będzie odczytana.
Dobrze aby powstała funkcjonalność, przetwarzająca wszystkie interfejsy w poszukiwaniu konfiguracji sieci...

**Comment by seweryn-S** [comment]
Problem przypomina ten z wyborem dysków niestety. Możliwy jest przegląd kart, ale która jest ta właściwa? A jeśli na kilku będzie odpowiadał serwer DHCP? Więc automatycznie będzie trudno. 
Początek startu z sieci nie używa ipxe tylko standardowego PXE, dopiero z niego ładowany jest ipxe gdzie już można wiele skonfigurować. PXE można konfigurować tylko w BIOS-ie więc to nie należy do projektu.

IPXE. Do dyspozycji jest plik boot.ipxe. W nim można zapisać wszystkie polecenia ipxe. W momencie gdy zaczyna być czytany wcześniej był już wykonane polecenia ipxe z wbudowanego pliku boipxe/ipxe.embed.ipxe. Więc podstawowy interfejs jest już zainicjowany, ale można wszystko zmienić. Zachęcam do zapoznania się w końcu z możliwościami ipxe :)
